kafka:
  brokers:
    - "localhost:9092"
  group_id: "dispatcher-group"
  topic_file: "E:\\practice\\project_viettel\\Discovery_Playwright\\topics.json"

dispatcher:
  num_in_batch: 10
  num_window: 3
  rate_Error: 0.7


